### ISSUE TITLE
funktioniert nicht

### ISSUE THREAD

**Issue by siragileII** [wubbl0rz/EpgChamp#1]
moin,
wenn ich das programm starte funktioniert's nicht.

[Hier video fuer reproduce](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by wubbl0rz** [comment]
![image](https://user-images.githubusercontent.com/30373916/172020314-bab94747-d6f1-4db7-b7e4-efccea0e7b07.png)
